# constants.py

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Аркадные Гонки"


CAMERA_LERP = 0.1  # Плавность камеры (меньше = плавнее)


TEXTURE_CHANGE_DELAY = 0.1


PLAYER_SPEED = 6.0
PLAYER_SCALE = 0.5
# TRACK 1
PLAYER_START_X_TRACK_1 = 1056
PLAYER_START_Y_TRACK_1 = 80
# TRACK 2
PLAYER_START_X_TRACK_2 = 482
PLAYER_START_Y_TRACK_2 = 883